name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-java@v1
      with:
        java-version: '11.0.4'
        architecture: x64
    - uses: ./action-a
      env:
        MY_NAME: "Simon Boisen"
    - run: java --version
    - run: curl -L -O https://github.com/sbt/sbt/releases/download/v1.2.8/sbt-1.2.8.tgz
    - run: tar -xf sbt-1.2.8.tgz
    - run: ./sbt/bin/sbt version
